#!/usr/bin/env node
const fs = require('fs')
function read(path){
    fs.readFile(path, { encoding: 'utf-8' }, (err, data) => {
        if(err) {
            console.log('ERROR', err)
        }else {
            console.log(data.split('\n').length)
        }
    })
}